// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define POINTING_DEVICE_ROTATION_90
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_TASK_THROTTLE_MS 8
#define CIRQUE_PINNACLE_TAP_ENABLE

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define MOUSEKEY_WHEEL_DELTA 4

#define RGB_MATRIX_MODE_NAME_ENABLE
